### ISSUE TITLE
rules/klayout/drc/run_drc.py: bugs,issues: subprocess exit-status checking, --topcell arg ignored, klayout version check fails

### ISSUE THREAD

**Issue by sto6** [efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr#4]
## Specifications
- Version: branch=main 132dc73 [origin/main] Merge pull request #31 from efabless/main
- Platform: centos 7.9.2009, Python 3.6.8, KLayout 0.27.12
## Steps to Reproduce the Problem

```
ENHANCEMENT: Please add (optional) --outdir cmd-line option, to specify the directory in which
to write the .lyrdb error marker files.
TYPO: assesed -> assessed

BUG, misleading results. Due fail to check subprocess exit-status, example shows (forced) out-of-memory.
Gives false result, since many rules were not checked, but results implies those rules were clean.
Memory limits can manifest also as SIGKILL, SIGSEGV, so reporting the numeric klayout exit-status 
is important, helpful towards understanding what happened. If the kernel's oom-killer killed the process
the exit-status seen by python would be -9 (not shown below).
The run_drc.py exit-status should also be non-zero in this case.

$ ulimit -Sv1600000
$ python3 run_drc.py --path=./testing/testcases/0.0.DM000013_13_1P6M_30kA_MIMB_BALL.gds.gz --gf180mcu=C; echo $?
28-Nov-2022 14:03:33 | INFO    | Your Klayout version is: KLayout 0.27.12
28-Nov-2022 14:03:37 | INFO    | Running main Global Foundries 180nm MCU runset on design 0.0.DM000013_13_1P6M_30kA_MIMB_BALL.gz on cell 0_0_DM000013_13_1P6M_30kA_MIMB_BALL:
2022-11-28 14:03:39 -0800: Memory Usage (673076K) : Starting running GF180MCU Klayout DRC runset on ./testing/testcases/0.0.DM000013_13_1P6M_30kA_MIMB_BALL.gds.gz
2022-11-28 14:03:40 -0800: Memory Usage (748164K) : Loading database to memory is complete.
2022-11-28 14:03:40 -0800: Memory Usage (748164K) : GF180MCU Klayout DRC runset output at: 0.0.DM000013_13_1P6M_30kA_MIMB_BALL.gz_main_drc_gfC.lyrdb
...
2022-11-28 14:05:12 -0800: Memory Usage (1197292K) : Executing rule CO.1
2022-11-28 14:05:25 -0800: Memory Usage (1428744K) : Executing rule CO.2a
ERROR: In /tmp/gits/globalfoundries-pdk-libs-gf180mcu_fd_pr/rules/klayout/drc/gf180mcu.drc: 'space': std::bad_alloc in Region::space_check
ERROR: 'space': std::bad_alloc in Region::space_check in Executable::execute
  /tmp/gits/globalfoundries-pdk-libs-gf180mcu_fd_pr/rules/klayout/drc/gf180mcu.drc:2264:in `execute'
  :/built-in-macros/drc_interpreters.lym:27:in `instance_eval'
  :/built-in-macros/drc_interpreters.lym:27:in `execute'
28-Nov-2022 14:05:42 | ERROR   |
Total # of DRC violations in gf180mcu.drc is 186. Please check 0.0.DM000013_13_1P6M_30kA_MIMB_BALL.gz_main_drc_gfC.lyrdb file For more details
28-Nov-2022 14:05:42 | INFO    | Klayout GDS DRC Not Clean
28-Nov-2022 14:05:42 | INFO    | Violated rules are : ['DN.1', 'DN.2b_', 'DN.3', 'LPW.1_3.3V', 'LPW.1_5V', 'LPW.2a_3.3V_', 'LPW.2a_5V_', 'LPW.3_3.3V', 'LPW.3_5V', 'LPW.5_3.3V', 'LPW.11', 'LPW.12', 'NW.1a_3.3V', 'NW.1a_5V', 'NW.1b_3.3V', 'NW.1b_5V', 'NW.2b_3.3V_', 'NW.2b_5V_', 'NW.3_3.3V', 'NW.3_5V', 'NW.4_3.3V', 'NW.4_5V', 'NW.5_3.3V', 'NW.5_5V', 'NW.6', 'DF.1a_3.3V', 'DF.1a_5V', 'DF.1c_3.3V', 'DF.2a_3.3V', 'DF.2a_5V', 'DF.2b_3.3V', 'DF.2b_5V', 'DF.3a_3.3V', 'DF.3a_5V', 'DF.3b_3.3V', 'DF.3b_5V', 'DF.3c_3.3V', 'DF.3c_5V', 'DF.4a_3.3V', 'DF.4a_5V', 'DF.4b_3.3V', 'DF.4b_5V', 'DF.4c_3.3V', 'DF.4c_5V', 'DF.4d_3.3V', 'DF.4d_5V', 'DF.4e_3.3V', 'DF.4e_5V', 'DF.5_3.3V', 'DF.5_5V', 'DF.6_3.3V', 'DF.6_5V', 'DF.7_3.3V', 'DF.7_5V', 'DF.8_3.3V', 'DF.8_5V', 'DF.9_3.3V', 'DF.9_5V', 'DF.10_3.3V', 'DF.10_5V', 'DF.11_3.3V', 'DF.11_5V', 'DF.12_3.3V', 'DF.12_5V', 'DF.13_3.3V', 'DF.14_3.3V', 'DF.14_5V', 'DF.16_3.3V', 'DF.16_5V', 'DF.17_3.3V', 'DF.17_5V', 'DF.18_3.3V', 'DF.18_5V', 'DF.19_3.3V', 'DF.19_5V', 'DV.1', 'DV.2', 'DV.3', 'DV.5', 'DV.6', 'DV.7', 'DV.8', 'DV.9', 'PL.1_3.3V', 'PL.1_5V', 'PL.1a_3.3V', 'PL.2_3.3V', 'PL.2_5V', 'PL.3a_3.3V', 'PL.3a_5V', 'PL.4_3.3V', 'PL.4_5V', 'PL.5a_3.3V', 'PL.5a_5V', 'PL.5b_3.3V', 'PL.5b_5V', 'PL.6', 'PL.7_3.3V', 'PL.7_5V', 'PL.9', 'PL.11', 'PL.12', 'NP.1', 'NP.2', 'NP.3a', 'NP.3bi', 'NP.3bii', 'NP.3ci', 'NP.3cii', 'NP.3d', 'NP.3e', 'NP.4a', 'NP.4b', 'NP.5a', 'NP.5b', 'NP.5ci', 'NP.5cii', 'NP.5di', 'NP.5dii', 'NP.6', 'NP.7', 'NP.8a', 'NP.8b', 'NP.9', 'NP.10', 'NP.11', 'NP.12', 'PP.1', 'PP.2', 'PP.3a', 'PP.3bi', 'PP.3bii', 'PP.3ci', 'PP.3cii', 'PP.3d', 'PP.3e', 'PP.4a', 'PP.4b', 'PP.5a', 'PP.5b', 'PP.5ci', 'PP.5cii', 'PP.5di', 'PP.5dii', 'PP.6', 'PP.7', 'PP.8a', 'PP.8b', 'PP.9', 'PP.10', 'PP.11', 'PP.12', 'SB.1', 'SB.2', 'SB.3', 'SB.4', 'SB.5a', 'SB.5b', 'SB.6', 'SB.7', 'SB.8', 'SB.9', 'SB.10', 'SB.11', 'SB.12', 'SB.13', 'SB.14a', 'SB.14b', 'SB.15a', 'SB.15b', 'SB.16', 'ESD.1', 'ESD.2', 'ESD.3a', 'ESD.3b', 'ESD.4a', 'ESD.4b', 'ESD.5a', 'ESD.5b', 'ESD.6', 'ESD.7', 'ESD.8', 'ESD.pl', 'ESD.9', 'ESD.10', 'CO.1']

0

BUG, the --topcell arg does not work, it is ignored, unused: No way to run on a gds with
multiple top-cells. No way to run just on a subcell of GDS having just one top-cell.

$ python3 run_drc.py --path=./testing/sc_testcases/gf180mcu_fd_sc_mcu7t5v0.gds --gf180mcu=C --topcell=AND4_X4_7T5P0
28-Nov-2022 13:31:11 | INFO    | Your Klayout version is: KLayout 0.27.12
## File has multiple topcell names
## Will have to stop.

BUG, Script does not set non-zero exit code on errors.

$ python3 run_drc.py --path=./testing/sc_testcases/gf180mcu_fd_sc_mcu7t5v0.gds --gf180mcu=C
28-Nov-2022 13:33:03 | INFO    | Your Klayout version is: KLayout 0.27.12
## File has multiple topcell names
## Will have to stop.
$ echo $?
0

$ python3 run_drc.py --path=/does/not/exist --gf180mcu=None
28-Nov-2022 13:34:16 | ERROR   | The input GDS file path doesn't exist, please recheck.
$ echo $?
0

BUG, Does not check return status of subprocesses.

$ chmod a-r junk.gds.gz
$ python3 run_drc.py --path=junk.gds.gz --gf180mcu=C
28-Nov-2022 13:35:33 | INFO    | Your Klayout version is: KLayout 0.27.12
ERROR: Unable to open file: junk.gds.gz (errno=13) in Layout::read
  /tmp/gits/globalfoundries-pdk-libs-gf180mcu_fd_pr/rules/klayout/drc/utils/get_top_cell_names.rb:16:in `read'
  /tmp/gits/globalfoundries-pdk-libs-gf180mcu_fd_pr/rules/klayout/drc/utils/get_top_cell_names.rb:16:in `<main>'
Traceback (most recent call last):
  File "run_drc.py", line 259, in <module>
    main()
  File "run_drc.py", line 172, in main
    topcell_name = tc_list[0]
IndexError: list index out of range

Show that the klayout on get_top_cell_names.rb script is returning exit-status 1:

$ klayout -b -r utils/get_top_cell_names.rb -rd infile=junk.gds.gz
ERROR: Unable to open file: junk.gds.gz (errno=13) in Layout::read
  utils/get_top_cell_names.rb:16:in `read'
  utils/get_top_cell_names.rb:16:in `<main>'
$ echo $?
1

BUG, klayout version check improper, does not flag 0.26.x as old, improperly flags 0.28.x as old.

$ klayout -b -v
KLayout 0.26.11
$ python3 run_drc.py --path=junk.gds.gz --gf180mcu=C
28-Nov-2022 13:41:51 | INFO    | Your Klayout version is: KLayout 0.26.11
28-Nov-2022 13:41:51 | INFO    | Running main Global Foundries 180nm MCU runset on design junk.gz on cell KLayout 0.26.11:
...

$ klayout -b -v
KLayout 0.28.1
$ python3 run_drc.py --path=junk.gds.gz --gf180mcu=C
28-Nov-2022 14:35:44 | INFO    | Your Klayout version is: KLayout 0.28.1
28-Nov-2022 14:35:44 | INFO    | Prerequisites at a minimum: KLayout 0.27.8
28-Nov-2022 14:35:44 | ERROR   | Using this klayout version has not been assesed in this development. Limits are unknown
28-Nov-2022 14:35:44 | INFO    | Running main Global Foundries 180nm MCU runset on design junk.gz on cell KLayout 0.28.1:
...

BUG, Version check (klayout -v) should be done with: klayout -b -v
Old enough versions can't report the version in non-X-windows mode without explicit -b also.
```

**Comment by atorkmabrains** [comment]
@sto6 All the issues mentioned above has been addressed in the latest version pushed.

**Comment by atorkmabrains** [comment]
@sto6 

Commit link is at:
https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr/commit/6aa5432a368138e9e6b899daade4c666f5ec808a
